Repository martai4/IO-I42-Alpha-SQC, pull requests merged in 2021-12, with the labels that each got.

#6 IIAS 28 gotowy
  logback.xml~
  src/main/java/pl/put/poznan/checker/app/ScenarioQualityCheckerApplication.java
  src/main/java/pl/put/poznan/checker/debug/ScenarioFileLoader.java
  src/main/java/pl/put/poznan/checker/logic/LengthVisitor.java
  src/main/java/pl/put/poznan/checker/logic/ScenarioQualityChecker.java
  src/main/java/pl/put/poznan/checker/scenario/Scenario.java
  src/main/java/pl/put/poznan/checker/scenario/ScenarioRepository.java
  src/main/java/pl/put/poznan/checker/scenario/ScenarioTextifier.java
  src/main/java/pl/put/poznan/checker/scenario/Step.java
  src/main/java/pl/put/poznan/checker/scenario/SubScenario.java
  src/main/java/pl/put/poznan/checker/scenario/VisitableElement.java
  src/main/java/pl/put/poznan/checker/scenario/Visitor.java
  src/test/java/pl/put/poznan/checker/debug/ScenarioFileLoaderTest.java
  src/test/java/pl/put/poznan/checker/logic/ScenarioQualityCheckerTest.java
  testScenario.txt
Labels: enhancement

#5 IIAS-31 Jako analityk mogę pobrać scenariusz w postaci tekstu.
  src/main/java/pl/put/poznan/checker/logic/ScenarioTextifier.java
  src/main/java/pl/put/poznan/checker/rest/ScenariosController.java
  src/main/java/pl/put/poznan/checker/scenario/ScenarioTextifier.java
  src/test/java/pl/put/poznan/checker/scenario/ScenarioTextifierTest.java
Labels: documentation, enhancement

#10 IIAS-30
  src/main/java/pl/put/poznan/checker/scenario/Scenario.java
  src/main/java/pl/put/poznan/checker/scenario/Step.java
  src/main/java/pl/put/poznan/checker/scenario/SubScenario.java
  src/test/java/pl/put/poznan/checker/debug/ScenarioFileLoaderTest.java
  src/test/java/pl/put/poznan/checker/scenario/ScenarioTextCheck.java
  testScenario.txt
Labels: enhancement, needs improvements
